---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: octops
  namespace: {{ .Values.namespace }}
  labels:
    app: octops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: octops
  labels:
    app: octops
rules:
  - apiGroups: [ "" ]
    resources: [ "events" ]
    verbs: [ "create" ]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get", "watch"]
  - apiGroups: [ "" ]
    resources: [ "services" ]
    verbs: [ "list", "get", "create", "delete", "watch" ]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["list", "get", "create", "delete", "watch"]
  - apiGroups: ["agones.dev"]
    resources: ["gameservers","fleets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: octops
  labels:
    app: octops
subjects:
  - kind: User
    name: system:serviceaccount:{{ .Values.namespace }}:octops
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: octops
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: octops-ingress-controller
  name: octops-ingress-controller
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: octops-ingress-controller
  template:
    metadata:
      labels:
        app: octops-ingress-controller
    spec:
      serviceAccountName: octops
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: controller
          args:
            - --sync-period=15s
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "0.5"
              memory: "50Mi"
            limits:
              cpu: "1"
              memory: "150Mi"